# Trackname styling
<TrackName@Label>:
    color: 1, 1, 1, 1
    font_size: 16
    halign: 'left'
    valign: 'middle'
    text_size: self.size

<AudioPlayer>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: 20

        RecycleView:
            id: tracklist
            viewclass: 'TrackName'
            size_hint_y: None
            height: 200  # or use self.minimum_height if dynamic
            RecycleBoxLayout:
                orientation: 'vertical'
                default_size: None, 40
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height

                canvas.before:
                    Color:
                        rgba: 0.25, 0.25, 0.25, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
        
        BoxLayout:

            Button:
                text: "Play"
                size_hint: 0.2, 0.1
                on_press: root.play_audio(self)

            Button:
                text: "Pause"
                size_hint: 0.2, 0.1
                on_press: root.pause_audio(self)

            Button:
                text: "Previous"
                size_hint: 0.2, 0.1
                on_press: root.previous_track(self)

            Button:
                text: "Stop"
                size_hint: 0.2, 0.1
                on_press: root.stop_audio(self)

            Button:
                text: "Next"
                size_hint: 0.2, 0.1
                on_press: root.next_track(self)

<TrackItem@Label>:
    size_hint_y: None
    height: 40
    text_size: self.size
