#:import sp kivy.metrics.sp
#:set DFT_FONT "NotoSans-Medium.ttf"
#:set DFT_FONT_SIZE 16
#:set BTN_HEIGHT dp(32)

<Label>:
    font_name: DFT_FONT
    font_size: DFT_FONT_SIZE

<Button>:
    font_name: DFT_FONT
    font_size: DFT_FONT_SIZE
    size_hint_x: None
    size_hint_y: None
    height: BTN_HEIGHT
    width: dp(60)

# This is a class that is later instantiated. The TrackRow is NOT directly displayed here but LATER inside the RecycleView!
<TrackRow@BoxLayout>:
    index: 0
    text: ''
    duration: ''
    bg_color: 0.25, 0.25, 0.25, 1
    checked: False
    orientation: 'horizontal'
    size_hint_y: None
    height: 28
    spacing: 8


    # Highlight current track row
    canvas.before:
        Color:
            rgba: root.bg_color
        Rectangle:
            pos: self.pos
            size: self.size

    # Label area handles double click and shows background color
    Label:
        id: lbl
        text: root.text
        font_size: DFT_FONT_SIZE
        size_hint_x: 0.76
        padding: 30, 10, 10, 10
        valign: 'middle'
        text_size: self.size
        on_touch_down:
            if self.collide_point(*args[1].pos): app.root.row_pressed(root.index, args[1])

    # Duration column
    Label:
        id: duration
        text: root.duration
        font_size: DFT_FONT_SIZE
        size_hint_x: 0.12
        padding: 10
        valign: 'middle'
        text_size: self.size

    # Checkbox column
    CheckBox:
        id: cb
        size_hint_x: 0.12
        active: root.checked
        on_active: app.root.on_row_checkbox(root.index, self.active)


<AudioPlayer>:
    GridLayout:
        cols: 1
        rows: 3
        spacing: 0
        padding: 0

        canvas.before:
            Color:
                rgba: 0.25, 0.25, 0.25, 1
            Rectangle:
                pos: self.pos
                size: self.size

        
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: BTN_HEIGHT + 8
            spacing: dp(8)
            padding: dp(8), dp(4)   # left/right, top/bottom

            Button:
                text: "Open"
                on_release: root.get_media()

            Button:
                text: "^"
                on_release: root.move_track_up(self)

            Button:
                text: "v"
                on_release: root.move_track_down(self)

            Button:
                text: "X"
                background_normal: ''
                background_color: 1, 0, 0, 1
                on_release: app.root.remove_media(root.index)

        BoxLayout:
            index: 0
            text: ''
            bg_color: 0.25, 0.25, 0.25, 1
            checked: False
            orientation: 'horizontal'
            size_hint_y: None
            height: 28
            spacing: 8

            Label:
                id: title_header
                text: 'Title'
                bold: True
                size_hint_x: 0.76
                padding: 10
                valign: 'middle'
                text_size: self.size

            Label:
                id: duration_header
                text: 'Duration'
                bold: True
                size_hint_x: 0.12
                padding: 10
                valign: 'middle'
                text_size: self.size

            Label:
                id: repeat_header
                text: 'Repeat'
                bold: True
                size_hint_x: 0.12
                padding: 10
                valign: 'middle'
                text_size: self.size



        RecycleView:
            id: tracklist
            viewclass: 'TrackRow'
            size_hint_y: 
            height: 200  # or use self.minimum_height if dynamic
            RecycleBoxLayout:
                orientation: 'vertical'
                default_size: None, 28
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height

                canvas.before:
                    Color:
                        rgba: 0.25, 0.25, 0.25, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: BTN_HEIGHT + 8
            spacing: dp(8)
            padding: dp(8), dp(4)   # left/right, top/bottom

            Button:
                text: ">"
                background_color: 0, 0, 0, 1
                on_release: root.play_audio(self)

            Button:
                text: "||"
                background_color: 0, 0, 0, 1
                on_release: root.pause_audio(self)

            Button:
                text: "<<|"
                background_color: 0, 0, 0, 1
                on_release: root.previous_track(self)

            Button:
                text: "[ ]"
                background_color: 0, 0, 0, 1
                on_release: root.stop_audio(self)

            Button:
                text: "|>>"
                background_color: 0, 0, 0, 1
                on_press: root.next_track(self)

<TrackItem@Label>:
    size_hint_y: None
    height: 40
    text_size: self.size
